#!/bin/bash
 
# Rebuilds parbaked project from it's git repositories
# Jason D Snider <jason@jasonsnider.com>

#Load the config file
echo 'Loading configuration...'
source config

COMMAND="$1"

if [ $# -ne 1 ]
then
    echo "Usage: $0 {COMMAND}"
    echo "What would you like to do? (build, status, push, pull)."
    exit 1
else
	echo "The installer is running with the $COMMAND command"
fi

# Remove all project files and reinstall them from the repositories
if [ "$COMMAND" == "build" ] 
then
	rm "$PROJECT_PATH/app" -fR
	for REPO in $REPOS
	do
		IFS=',' read -a array <<< "$REPO"
		cd $PROJECT_PATH${array[0]} && git clone ${array[2]} ${array[1]}
	done
fi 

# Pull the latest updates from all repositories
if [ "$COMMAND" == "pull" ]
then

        for REPO in $REPOS
        do
                IFS=',' read -a array <<< "$REPO"
                cd $PROJECT_PATH${array[0]}/${array[1]} && git pull origin master
        done
fi

# Check the status of all repositories to which you have write access
if [ "$COMMAND" == "status" ] 
then
        for REPO in $REPOS
        do
                IFS=',' read -a array <<< "$REPO"
		if [ "${array[3]}" == "write" ] 
		then
                	cd $PROJECT_PATH${array[0]}/${array[1]} && git status
		fi
        done
fi

# Push all changes to all repositories to which you have wrte access
if [ "$COMMAND" == "push" ]
then
        for REPO in $REPOS
        do
                IFS=',' read -a array <<< "$REPO"
                if [ "${array[3]}" == "write" ]
                then
                        cd $PROJECT_PATH${array[0]}/${array[1]} && git pull origin master
                fi
        done
fi

if [ "AS" == "root" ]
then
	su root

	chown "$APACHE_PROCESS":"$USER" -fR "$PROJECT_PATH"/lib/Cake/Cache -fR
	chown "$APACHE_PROCESS":"$USER" -fR "$PROJECT_PATH"/app/tmp -fR
	chown "$APACHE_PROCESS":"$USER" -fR "$PROJECT_PATH"/app/Vendor/HtmlPurifier/library/HTMLPurifier/DefinitionCache/Serializer -fR
else
        sudo chown "$APACHE_PROCESS":"$USER" -fR "$PROJECT_PATH"/lib/Cake/Cache -fR
        sudo chown "$APACHE_PROCESS":"$USER" -fR "$PROJECT_PATH"/app/tmp -fR
        sudo chown "$APACHE_PROCESS":"$USER" -fR "$PROJECT_PATH"/app/Vendor/HtmlPurifier/library/HTMLPurifier/DefinitionCache/Serializer -fR

fi






