#!/bin/bash

PROJECT_PATH="/var/www/parbake.org" #Path to the project, the folder into which the app directory will be deployed
APACHE_PROCESS="www-data" #Apache process, probably www-data
USER="user" #probably the user name you used to log on to this machine with
AS='sudo' #sudo or root depending on the OS Ubuntu would probably be sudo, Debian would probably be root

#All of the repositories that make up your project
#Path, Directory, Repository, Privs (by default all privs are read only) 
REPOS="
	--App
	/,app,git@github.com:parbake/parbake.git,read
	--Config
	/app,Config,git@github.com:parbake/Config.git,read
	--Parbake_Plugins
	/app/Plugin,Contents,git@github.com:parbake/Contents-plugin.git,read
	/app/Plugin,Users,git@github.com:parbake/Users-plugin.git,read
	/app/Plugin,Utilities,git@github.com:parbake/Utilities-plugin.git,read
	--Third_Party_Plugins
	/app/Plugin,AuditLog,git@github.com:jasonsnider/CakePHP-Audit-Log-Plugin.git,read
	--CakePHP_and_CakeDC_Plugins
	/app/Plugin,Tags,https://github.com/CakeDC/tags.git,read
	/app/Plugin,Search,https://github.com/CakeDC/search.git,read
	/app/Plugin,DebugKit,https://github.com/cakephp/debug_kit.git,read
	--Vendors
	/app/Vendor,HtmlPurifier,git://repo.or.cz/htmlpurifier.git,read
"


