#!/bin/bash
# jasonsnider.com
PROJECT_PATH="/var/www/jasonsnider.com"
APACHE_PROCESS="www-data"
USER="jasonsnider"
AS="sudo" #root or sudo

REPOS="
	--App
	/,app,git@github.com:parbake/parbake.git,write
	--Config
	/app,Config,ssh://git@bitbucket.org/jasonsnider/config-jasonsnider.com.git,write
	--JSC_Plugins
	/app/Plugin,Contents,git@github.com:parbake/Contents-plugin.git,write
	/app/Plugin,Users,git@github.com:parbake/Users-plugin.git,write
	/app/Plugin,Utilities,git@github.com:parbake/Utilities-plugin.git,write
	--Third_Party_Plugins
	/app/Plugin,AuditLog,git@github.com:jasonsnider/CakePHP-Audit-Log-Plugin.git,read
	--CakePHP_and_CakeDC_Plugins
	/app/Plugin,Tags,https://github.com/CakeDC/tags.git,read
	/app/Plugin,Search,https://github.com/CakeDC/search.git,read
	/app/Plugin,DebugKit,https://github.com/cakephp/debug_kit.git,read
	--Vendors
	/app/Vendor,HtmlPurifier,git://repo.or.cz/htmlpurifier.git,read
	--Project_specific_repositories
	/app/Plugin,Jsc,git@github.com:jasonsnider/Jsc-plugin.git,write
	--Project_Theme(s)
	/app/View/Themed,JasonSniderTbs,git@github.com:jasonsnider/JasonSniderTbs-theme.git,write
"

#	/app/Plugin,JSC,git@github.com:jasonsnider/JSC-plugin.git,write
