#!/bin/bash
# Configure the build script
PROJECT_PATH="/var/www/jasonsnider.com"
APACHE_PROCESS="www-data"
USER="jsnider"
AS="sudo" #root or sudo


REPOS="
	##App
	/,app,git@github.com:parbake/parbake.git,write
	##Config - AFTER INSTALL CHANGE THIS TO A PRIVATE REPOSITORY
	/app,Config,ssh://git@bitbucket.org/jasonsnider/config-sarahsniderlmt.com.git,write
	##Parbake Plugins
	/app/Plugin,Contents,git@github.com:parbake/Contents-plugin.git,write
	/app/Plugin,Users,git@github.com:parbake/Users-plugin.git,write
	/app/Plugin,Utilities,git@github.com:parbake/Utilities-plugin.git,write
	##Third Party Plugins
	/app/Plugin,AuditLog,git@github.com:jasonsnider/CakePHP-Audit-Log-Plugin.git,read
	##CakePHP and CakeDC Plugins
	/app/Plugin,Tags,https://github.com/CakeDC/tags.git,read
	/app/Plugin,Search,https://github.com/CakeDC/search.git,read
	/app/Plugin,DebugKit,https://github.com/cakephp/debug_kit.git,read
	##Vendors
	/app/Vendor,HtmlPurifier,git://repo.or.cz/htmlpurifier.git,read
	## Project specific repositories
	/app/Plugin,Sarah,git@github.com:jasonsnider/Sarah-plugin.git,write
	## Project Theme(s)
	/app/View/Themed,SarahSnider,git@github.com:jasonsnider/SarahSnider-theme.git,write
"


